name: CI
on:
  push:
    branches: [master, release/**]
  pull_request:
    branches: [master, release/**]
jobs:
  # Build and Test the 'cucumber-tsflow' package
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cucumberVersion: ["^10", "^11", "^12", "^13"]
    steps:
      - uses: actions/checkout@v7.0.0
      - uses: actions/setup-node@v6.4.0
        with:
          node-version: 22
      - name: Install npm packages
        run: |-
          npm ci
          npm install @cucumber/cucumber@${{ matrix.cucumberVersion }}
      - name: Build
        run: npm run build
      - name: Run specification tests
        run: npm test
